use_frameworks!

platform :ios, '8.0'

target 'podTestLibrary_Example' do
  pod 'podTestLibrary', :path => '../'
  pre_install do |installer|
    # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
    def installer.verify_no_static_framework_transitive_dependencies; end
  end
end
